//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harvy.Ordonez.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.InvoiceDetail = new HashSet<InvoiceDetail>();
        }
    
        public int IdItem { get; set; }
        public string TypeItem { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string Photo { get; set; }
        public Nullable<bool> IsTax { get; set; }
        public Nullable<bool> IsInventory { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpadteAt { get; set; }
        public Nullable<System.DateTime> DeleteAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetail { get; set; }
    }
}
